### ISSUE TITLE
Assessment Results

### ISSUE THREAD

**Issue by rwarbelow** [alexandermathieu/mod_0_skills#1]
# Checklist/Rubric

#### Part I: Creating Directories and Files; Initializing Git and Pushing to GitHub
* [x]  Directories are named correctly.
* [x]  Files are named correctly.
* [x]  Files and directories are structured correctly.
* [x]  Initial commit was made.
* [x]  Initial commit was pushed to GitHub.

#### Part II: Top Down Design
* [x]  Larger processes were broken into smaller layers.
* [x]  Changes were added and committed with a properly formatted commit message starting with a verb and a capital letter.
* [x]  Changes were pushed to Github.

#### Part III: Classes in a System
* [x]  Directories and files were named and structured correctly.
* [x]  The attributes chosen for **Class #1** represent states or characteristics.
* [x]  The attributes chosen for **Class #2** represent states or characteristics.
> The only thing I might suggest is moving `closing_soon?` to a method that performs a calculation using the `hours_of_operation` hash. Generally, if a characteristic is frequently changing (like `closing_soon?`), it should be the result of some sort of method. 
* [x]  The attributes chosen for **Class #3** represent states or characteristics.
* [x]  The methods chosen for **Class #1** represent behaviors or actions.
* [x]  The methods chosen for **Class #2** represent behaviors or actions.
* [x]  The methods chosen for **Class #3** represent behaviors or actions.
* [x]  Data type (string, integer, boolean, array, hash/object, datetime) were identified for each attribute in all three classes.
* [x]  Individual changes were added and committed separately with a properly formatted commit message.
> We're ignore all of the git fixing in the middle 😂 
* [x]  Changes were pushed to Github.

**Mod 0 Technical Assessment Results**

* [x]   Technical Ready
* [ ]   Pending
* [ ]   Not Ready

**Comment by alexandermathieu** [comment]
Understood, thank you!
